# Generated by Django 5.1.6 on 2025-04-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadinventory',
            name='pave_type',
            field=models.CharField(blank=True, db_column='paveType', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roadinventory',
            name='pave_width',
            field=models.CharField(blank=True, db_column='paveWidth', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roadinventory',
            name='row',
            field=models.CharField(blank=True, db_column='row', max_length=255, null=True),
        ),
    ]
